version: "3.9"

services:
  conversation_ruler_app:
    container_name: conversation_ruler_app
    build: .
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=el que dios ponga en tu corazon 
      - PG_DB=chatbot
      - PG_PORT=5432
      - PG_HOST=en algun lugar 
      - DOCKER_DEFAULT_PLATFORM=linux/amd64


#    depends_on:
#      - db

#  db:
#    container_name: db
#    image: postgres:12
#    environment:
#      - POSTGRES_DB=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

#volumes:
#  pgdata: {}
